# Generated by Django 6.0.7 on 2026-07-14 23:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA_VENDA', 'Saída por venda'), ('PERDA', 'Perda'), ('DEVOLUCAO', 'Devolução'), ('PRODUCAO', 'Produção concluída'), ('AJUSTE_ENTRADA', 'Ajuste de entrada'), ('AJUSTE_SAIDA', 'Ajuste de saída')], max_length=30, verbose_name='Tipo de movimentação')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('saldo_anterior', models.PositiveIntegerField(verbose_name='Saldo anterior')),
                ('saldo_resultante', models.PositiveIntegerField(verbose_name='Saldo resultante')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo ou observação')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da movimentação')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('variacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='produtos.variacaoproduto', verbose_name='Variação')),
            ],
            options={
                'verbose_name': 'Movimentação de estoque',
                'verbose_name_plural': 'Movimentações de estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
    ]
