# Generated by Django 6.0.7 on 2026-07-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_movimentacaoestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo_origem',
            field=models.CharField(choices=[('FABRICACAO_PROPRIA', 'Fabricação própria'), ('REVENDA', 'Revenda')], default='FABRICACAO_PROPRIA', max_length=30, verbose_name='Tipo de origem'),
        ),
    ]
