# Generated by Django 6.0.7 on 2026-07-23 19:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
        ('produtos', '0003_produto_tipo_origem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposicaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_utilizada', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantidade utilizada')),
                ('percentual_perda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Perda prevista (%)')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composicoes_produtos', to='insumos.materiaprima', verbose_name='Matéria-prima')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicoes', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Composição do produto',
                'verbose_name_plural': 'Composições dos produtos',
                'ordering': ['materia_prima__nome'],
                'constraints': [models.UniqueConstraint(fields=('produto', 'materia_prima'), name='materia_prima_unica_por_produto')],
            },
        ),
    ]
