# Generated by Django 6.0.7 on 2026-07-23 20:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0004_composicaoproduto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPrecificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Configuração principal', max_length=100, verbose_name='Nome')),
                ('salario_mensal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Salário mensal considerado')),
                ('horas_trabalhadas_dia', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Horas trabalhadas por dia')),
                ('dias_trabalhados_semana', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Dias trabalhados por semana')),
                ('custos_fixos_mensais', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Custos fixos mensais')),
                ('producao_mensal_estimada', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Produção mensal estimada em peças')),
                ('percentual_comissao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Comissão (%)')),
                ('percentual_impostos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Impostos (%)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
            ],
            options={
                'verbose_name': 'Configuração de precificação',
                'verbose_name_plural': 'Configurações de precificação',
                'ordering': ['-ativo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PrecificacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_producao_minutos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tempo de produção em minutos')),
                ('outros_custos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Outros custos')),
                ('tipo_margem', models.CharField(choices=[('PERCENTUAL', 'Percentual sobre o custo'), ('VALOR_FIXO', 'Valor fixo')], default='PERCENTUAL', max_length=20, verbose_name='Tipo de margem')),
                ('valor_margem', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Margem desejada')),
                ('custo_materiais', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Custo dos materiais')),
                ('custo_mao_obra', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Custo da mão de obra')),
                ('custo_fixo_rateado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Custo fixo rateado')),
                ('custo_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Custo base')),
                ('lucro_estimado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Lucro estimado')),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Comissão')),
                ('valor_impostos', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Impostos')),
                ('preco_sugerido', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço sugerido')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('data_calculo', models.DateTimeField(auto_now_add=True, verbose_name='Data do cálculo')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precificacoes', to='precificacao.configuracaoprecificacao', verbose_name='Configuração utilizada')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precificacoes', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Precificação de produto',
                'verbose_name_plural': 'Precificações de produtos',
                'ordering': ['-data_calculo'],
            },
        ),
    ]
