# Generated by Django 6.0.7 on 2026-07-20 21:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
            ],
            options={
                'verbose_name': 'Categoria de matéria-prima',
                'verbose_name_plural': 'Categorias de matérias-primas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('M', 'Metro'), ('M2', 'Metro quadrado'), ('KG', 'Quilograma'), ('G', 'Grama'), ('L', 'Litro'), ('ML', 'Mililitro'), ('ROLO', 'Rolo'), ('PACOTE', 'Pacote'), ('CAIXA', 'Caixa')], max_length=10, verbose_name='Unidade de medida')),
                ('quantidade_estoque', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Quantidade em estoque')),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Estoque mínimo')),
                ('custo_unitario', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Custo unitário')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias_primas', to='insumos.categoriamateriaprima', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Matéria-prima',
                'verbose_name_plural': 'Matérias-primas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('ENTRADA', 'Entrada manual'), ('CONSUMO', 'Consumo na produção'), ('PERDA', 'Perda'), ('DEVOLUCAO', 'Devolução'), ('AJUSTE_ENTRADA', 'Ajuste de entrada'), ('AJUSTE_SAIDA', 'Ajuste de saída')], max_length=30, verbose_name='Tipo de movimentação')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantidade')),
                ('saldo_anterior', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Saldo anterior')),
                ('saldo_resultante', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Saldo resultante')),
                ('custo_unitario_movimentacao', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Custo unitário da movimentação')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo ou observação')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da movimentação')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='insumos.materiaprima', verbose_name='Matéria-prima')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_materia_prima', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Movimentação de matéria-prima',
                'verbose_name_plural': 'Movimentações de matérias-primas',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.AddConstraint(
            model_name='materiaprima',
            constraint=models.UniqueConstraint(fields=('nome', 'unidade_medida'), name='materia_prima_unica_por_unidade'),
        ),
    ]
