# Generated by Django 6.0.7 on 2026-07-23 21:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('ORCAMENTO', 'Orçamento'), ('PEDIDO', 'Pedido')], default='ORCAMENTO', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('ORCAMENTO', 'Orçamento'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('APROVADO', 'Aprovado'), ('EM_PRODUCAO', 'Em produção'), ('AGUARDANDO_ENTREGA', 'Aguardando retirada ou entrega'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='ORCAMENTO', max_length=30, verbose_name='Status')),
                ('data_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_prevista_entrega', models.DateField(blank=True, null=True, verbose_name='Previsão de entrega')),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor bruto')),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Desconto')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor total')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='vendas.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-data_pedido'],
            },
        ),
    ]
